# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from .changeable_attributes_py3 import ChangeableAttributes
    from .repository_attributes_py3 import RepositoryAttributes
    from .tag_attributes_base_py3 import TagAttributesBase
    from .tag_list_py3 import TagList
    from .tag_attributes_py3 import TagAttributes
    from .manifest_attributes_base_py3 import ManifestAttributesBase
    from .acr_manifests_py3 import AcrManifests
    from .manifest_attributes_py3 import ManifestAttributes
    from .refresh_token_py3 import RefreshToken
    from .access_token_py3 import AccessToken
    from .acr_error_info_py3 import AcrErrorInfo
    from .acr_errors_py3 import AcrErrors, AcrErrorsException
    from .repository_tags_py3 import RepositoryTags
    from .jwk_header_py3 import JWKHeader
    from .jwk_py3 import JWK
    from .image_signature_py3 import ImageSignature
    from .history_py3 import History
    from .repositories_py3 import Repositories
    from .deleted_repository_py3 import DeletedRepository
    from .fs_layer_py3 import FsLayer
    from .annotations_py3 import Annotations
    from .descriptor_py3 import Descriptor
    from .tag_attributes_tag_py3 import TagAttributesTag
    from .manifest_attributes_manifest_references_py3 import ManifestAttributesManifestReferences
    from .manifest_attributes_manifest_py3 import ManifestAttributesManifest
    from .manifest_changeable_attributes_py3 import ManifestChangeableAttributes
    from .manifest_py3 import Manifest
    from .platform_py3 import Platform
    from .manifest_list_attributes_py3 import ManifestListAttributes
    from .manifest_wrapper_py3 import ManifestWrapper
    from .manifest_list_py3 import ManifestList
    from .v2_manifest_py3 import V2Manifest
    from .oci_manifest_py3 import OCIManifest
    from .oci_index_py3 import OCIIndex
    from .v1_manifest_py3 import V1Manifest
except (SyntaxError, ImportError):
    from .changeable_attributes import ChangeableAttributes
    from .repository_attributes import RepositoryAttributes
    from .tag_attributes_base import TagAttributesBase
    from .tag_list import TagList
    from .tag_attributes import TagAttributes
    from .manifest_attributes_base import ManifestAttributesBase
    from .acr_manifests import AcrManifests
    from .manifest_attributes import ManifestAttributes
    from .refresh_token import RefreshToken
    from .access_token import AccessToken
    from .acr_error_info import AcrErrorInfo
    from .acr_errors import AcrErrors, AcrErrorsException
    from .repository_tags import RepositoryTags
    from .jwk_header import JWKHeader
    from .jwk import JWK
    from .image_signature import ImageSignature
    from .history import History
    from .repositories import Repositories
    from .deleted_repository import DeletedRepository
    from .fs_layer import FsLayer
    from .annotations import Annotations
    from .descriptor import Descriptor
    from .tag_attributes_tag import TagAttributesTag
    from .manifest_attributes_manifest_references import ManifestAttributesManifestReferences
    from .manifest_attributes_manifest import ManifestAttributesManifest
    from .manifest_changeable_attributes import ManifestChangeableAttributes
    from .manifest import Manifest
    from .platform import Platform
    from .manifest_list_attributes import ManifestListAttributes
    from .manifest_wrapper import ManifestWrapper
    from .manifest_list import ManifestList
    from .v2_manifest import V2Manifest
    from .oci_manifest import OCIManifest
    from .oci_index import OCIIndex
    from .v1_manifest import V1Manifest

__all__ = [
    'ChangeableAttributes',
    'RepositoryAttributes',
    'TagAttributesBase',
    'TagList',
    'TagAttributes',
    'ManifestAttributesBase',
    'AcrManifests',
    'ManifestAttributes',
    'RefreshToken',
    'AccessToken',
    'AcrErrorInfo',
    'AcrErrors', 'AcrErrorsException',
    'RepositoryTags',
    'JWKHeader',
    'JWK',
    'ImageSignature',
    'History',
    'Repositories',
    'DeletedRepository',
    'FsLayer',
    'Annotations',
    'Descriptor',
    'TagAttributesTag',
    'ManifestAttributesManifestReferences',
    'ManifestAttributesManifest',
    'ManifestChangeableAttributes',
    'Manifest',
    'Platform',
    'ManifestListAttributes',
    'ManifestWrapper',
    'ManifestList',
    'V2Manifest',
    'OCIManifest',
    'OCIIndex',
    'V1Manifest',
]
