# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model
from msrest.exceptions import HttpOperationError


class AcrErrors(Model):
    """Acr error response describing why the operation failed.

    :param errors: Array of detailed error
    :type errors: list[~azure.containerregistry.models.AcrErrorInfo]
    """

    _attribute_map = {
        'errors': {'key': 'errors', 'type': '[AcrErrorInfo]'},
    }

    def __init__(self, **kwargs):
        super(AcrErrors, self).__init__(**kwargs)
        self.errors = kwargs.get('errors', None)


class AcrErrorsException(HttpOperationError):
    """Server responsed with exception of type: 'AcrErrors'.

    :param deserialize: A deserializer
    :param response: Server response to be deserialized.
    """

    def __init__(self, deserialize, response, *args):

        super(AcrErrorsException, self).__init__(deserialize, response, 'AcrErrors', *args)
