# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AcrErrorInfo(Model):
    """Error information.

    :param code: Error code
    :type code: str
    :param message: Error message
    :type message: str
    :param detail: Error details
    :type detail: object
    """

    _attribute_map = {
        'code': {'key': 'code', 'type': 'str'},
        'message': {'key': 'message', 'type': 'str'},
        'detail': {'key': 'detail', 'type': 'object'},
    }

    def __init__(self, *, code: str=None, message: str=None, detail=None, **kwargs) -> None:
        super(AcrErrorInfo, self).__init__(**kwargs)
        self.code = code
        self.message = message
        self.detail = detail
