# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeletedRepository(Model):
    """Deleted repository.

    :param manifests_deleted: SHA of the deleted image
    :type manifests_deleted: list[str]
    :param tags_deleted: Tag of the deleted image
    :type tags_deleted: list[str]
    """

    _attribute_map = {
        'manifests_deleted': {'key': 'manifestsDeleted', 'type': '[str]'},
        'tags_deleted': {'key': 'tagsDeleted', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(DeletedRepository, self).__init__(**kwargs)
        self.manifests_deleted = kwargs.get('manifests_deleted', None)
        self.tags_deleted = kwargs.get('tags_deleted', None)
