# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Descriptor(Model):
    """Docker V2 image layer descriptor including config and layers.

    :param media_type: Layer media type
    :type media_type: str
    :param size: Layer size
    :type size: long
    :param digest: Layer digest
    :type digest: str
    :param urls: Specifies a list of URIs from which this object may be
     downloaded.
    :type urls: list[str]
    :param annotations:
    :type annotations: ~azure.containerregistry.models.Annotations
    """

    _attribute_map = {
        'media_type': {'key': 'mediaType', 'type': 'str'},
        'size': {'key': 'size', 'type': 'long'},
        'digest': {'key': 'digest', 'type': 'str'},
        'urls': {'key': 'urls', 'type': '[str]'},
        'annotations': {'key': 'annotations', 'type': 'Annotations'},
    }

    def __init__(self, *, media_type: str=None, size: int=None, digest: str=None, urls=None, annotations=None, **kwargs) -> None:
        super(Descriptor, self).__init__(**kwargs)
        self.media_type = media_type
        self.size = size
        self.digest = digest
        self.urls = urls
        self.annotations = annotations
