# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FsLayer(Model):
    """Image layer information.

    :param blob_sum: SHA of an image layer
    :type blob_sum: str
    """

    _attribute_map = {
        'blob_sum': {'key': 'blobSum', 'type': 'str'},
    }

    def __init__(self, *, blob_sum: str=None, **kwargs) -> None:
        super(FsLayer, self).__init__(**kwargs)
        self.blob_sum = blob_sum
