# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class History(Model):
    """A list of unstructured historical data for v1 compatibility.

    :param v1_compatibility: The raw v1 compatibility information
    :type v1_compatibility: str
    """

    _attribute_map = {
        'v1_compatibility': {'key': 'v1Compatibility', 'type': 'str'},
    }

    def __init__(self, *, v1_compatibility: str=None, **kwargs) -> None:
        super(History, self).__init__(**kwargs)
        self.v1_compatibility = v1_compatibility
