# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class JWK(Model):
    """A JSON web signature.

    :param jwk:
    :type jwk: ~azure.containerregistry.models.JWKHeader
    :param alg: The algorithm used to sign or encrypt the JWT
    :type alg: str
    """

    _attribute_map = {
        'jwk': {'key': 'jwk', 'type': 'JWKHeader'},
        'alg': {'key': 'alg', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(JWK, self).__init__(**kwargs)
        self.jwk = kwargs.get('jwk', None)
        self.alg = kwargs.get('alg', None)
