# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class JWKHeader(Model):
    """JSON web key parameter.

    :param crv: crv value
    :type crv: str
    :param kid: kid value
    :type kid: str
    :param kty: kty value
    :type kty: str
    :param x: x value
    :type x: str
    :param y: y value
    :type y: str
    """

    _attribute_map = {
        'crv': {'key': 'crv', 'type': 'str'},
        'kid': {'key': 'kid', 'type': 'str'},
        'kty': {'key': 'kty', 'type': 'str'},
        'x': {'key': 'x', 'type': 'str'},
        'y': {'key': 'y', 'type': 'str'},
    }

    def __init__(self, *, crv: str=None, kid: str=None, kty: str=None, x: str=None, y: str=None, **kwargs) -> None:
        super(JWKHeader, self).__init__(**kwargs)
        self.crv = crv
        self.kid = kid
        self.kty = kty
        self.x = x
        self.y = y
