# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .manifest import Manifest


class ManifestList(Manifest):
    """Returns the requested Docker multi-arch-manifest file.

    :param schema_version: Schema version
    :type schema_version: int
    :param media_type: Media type for this Manifest
    :type media_type: str
    :param manifests: List of V2 image layer information
    :type manifests:
     list[~azure.containerregistry.models.ManifestListAttributes]
    """

    _attribute_map = {
        'schema_version': {'key': 'schemaVersion', 'type': 'int'},
        'media_type': {'key': 'mediaType', 'type': 'str'},
        'manifests': {'key': 'manifests', 'type': '[ManifestListAttributes]'},
    }

    def __init__(self, **kwargs):
        super(ManifestList, self).__init__(**kwargs)
        self.media_type = kwargs.get('media_type', None)
        self.manifests = kwargs.get('manifests', None)
