# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManifestAttributesManifestReferences(Model):
    """Manifest attributes details.

    :param digest: Manifest digest
    :type digest: str
    :param architecture: CPU architecture
    :type architecture: str
    :param os: Operating system
    :type os: str
    """

    _attribute_map = {
        'digest': {'key': 'digest', 'type': 'str'},
        'architecture': {'key': 'architecture', 'type': 'str'},
        'os': {'key': 'os', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ManifestAttributesManifestReferences, self).__init__(**kwargs)
        self.digest = kwargs.get('digest', None)
        self.architecture = kwargs.get('architecture', None)
        self.os = kwargs.get('os', None)
