# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManifestChangeableAttributes(Model):
    """Changeable attributes.

    :param delete_enabled: Delete enabled
    :type delete_enabled: bool
    :param write_enabled: Write enabled
    :type write_enabled: bool
    :param list_enabled: List enabled
    :type list_enabled: bool
    :param read_enabled: Read enabled
    :type read_enabled: bool
    :param quarantine_state: Quarantine state
    :type quarantine_state: str
    :param quarantine_details: Quarantine details
    :type quarantine_details: str
    """

    _attribute_map = {
        'delete_enabled': {'key': 'deleteEnabled', 'type': 'bool'},
        'write_enabled': {'key': 'writeEnabled', 'type': 'bool'},
        'list_enabled': {'key': 'listEnabled', 'type': 'bool'},
        'read_enabled': {'key': 'readEnabled', 'type': 'bool'},
        'quarantine_state': {'key': 'quarantineState', 'type': 'str'},
        'quarantine_details': {'key': 'quarantineDetails', 'type': 'str'},
    }

    def __init__(self, *, delete_enabled: bool=None, write_enabled: bool=None, list_enabled: bool=None, read_enabled: bool=None, quarantine_state: str=None, quarantine_details: str=None, **kwargs) -> None:
        super(ManifestChangeableAttributes, self).__init__(**kwargs)
        self.delete_enabled = delete_enabled
        self.write_enabled = write_enabled
        self.list_enabled = list_enabled
        self.read_enabled = read_enabled
        self.quarantine_state = quarantine_state
        self.quarantine_details = quarantine_details
