# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManifestAttributesBase(Model):
    """Manifest details.

    :param digest: Manifest
    :type digest: str
    :param image_size: Image size
    :type image_size: long
    :param created_time: Created time
    :type created_time: str
    :param last_update_time: Last update time
    :type last_update_time: str
    :param architecture: CPU architecture
    :type architecture: str
    :param os: Operating system
    :type os: str
    :param media_type: Media type
    :type media_type: str
    :param config_media_type: Config blob media type
    :type config_media_type: str
    :param tags: List of tags
    :type tags: list[str]
    :param changeable_attributes: Changeable attributes
    :type changeable_attributes:
     ~azure.containerregistry.models.ChangeableAttributes
    """

    _attribute_map = {
        'digest': {'key': 'digest', 'type': 'str'},
        'image_size': {'key': 'imageSize', 'type': 'long'},
        'created_time': {'key': 'createdTime', 'type': 'str'},
        'last_update_time': {'key': 'lastUpdateTime', 'type': 'str'},
        'architecture': {'key': 'architecture', 'type': 'str'},
        'os': {'key': 'os', 'type': 'str'},
        'media_type': {'key': 'mediaType', 'type': 'str'},
        'config_media_type': {'key': 'configMediaType', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '[str]'},
        'changeable_attributes': {'key': 'changeableAttributes', 'type': 'ChangeableAttributes'},
    }

    def __init__(self, **kwargs):
        super(ManifestAttributesBase, self).__init__(**kwargs)
        self.digest = kwargs.get('digest', None)
        self.image_size = kwargs.get('image_size', None)
        self.created_time = kwargs.get('created_time', None)
        self.last_update_time = kwargs.get('last_update_time', None)
        self.architecture = kwargs.get('architecture', None)
        self.os = kwargs.get('os', None)
        self.media_type = kwargs.get('media_type', None)
        self.config_media_type = kwargs.get('config_media_type', None)
        self.tags = kwargs.get('tags', None)
        self.changeable_attributes = kwargs.get('changeable_attributes', None)
