# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ManifestAttributesManifest(Model):
    """List of manifest attributes.

    :param references: List of manifest attributes details
    :type references:
     list[~azure.containerregistry.models.ManifestAttributesManifestReferences]
    :param quarantine_tag: Quarantine tag name
    :type quarantine_tag: str
    """

    _attribute_map = {
        'references': {'key': 'references', 'type': '[ManifestAttributesManifestReferences]'},
        'quarantine_tag': {'key': 'quarantineTag', 'type': 'str'},
    }

    def __init__(self, *, references=None, quarantine_tag: str=None, **kwargs) -> None:
        super(ManifestAttributesManifest, self).__init__(**kwargs)
        self.references = references
        self.quarantine_tag = quarantine_tag
