# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .manifest import Manifest


class OCIIndex(Manifest):
    """Returns the requested OCI index file.

    :param schema_version: Schema version
    :type schema_version: int
    :param manifests: List of OCI image layer information
    :type manifests:
     list[~azure.containerregistry.models.ManifestListAttributes]
    :param annotations:
    :type annotations: ~azure.containerregistry.models.Annotations
    """

    _attribute_map = {
        'schema_version': {'key': 'schemaVersion', 'type': 'int'},
        'manifests': {'key': 'manifests', 'type': '[ManifestListAttributes]'},
        'annotations': {'key': 'annotations', 'type': 'Annotations'},
    }

    def __init__(self, **kwargs):
        super(OCIIndex, self).__init__(**kwargs)
        self.manifests = kwargs.get('manifests', None)
        self.annotations = kwargs.get('annotations', None)
