# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RefreshToken(Model):
    """RefreshToken.

    :param refresh_token: The refresh token to be used for generating access
     tokens
    :type refresh_token: str
    """

    _attribute_map = {
        'refresh_token': {'key': 'refresh_token', 'type': 'str'},
    }

    def __init__(self, *, refresh_token: str=None, **kwargs) -> None:
        super(RefreshToken, self).__init__(**kwargs)
        self.refresh_token = refresh_token
