# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TagAttributesTag(Model):
    """Tag.

    :param signature_record: SignatureRecord value
    :type signature_record: str
    """

    _attribute_map = {
        'signature_record': {'key': 'signatureRecord', 'type': 'str'},
    }

    def __init__(self, *, signature_record: str=None, **kwargs) -> None:
        super(TagAttributesTag, self).__init__(**kwargs)
        self.signature_record = signature_record
