# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TagList(Model):
    """List of tag details.

    :param registry: Registry name
    :type registry: str
    :param image_name: Image name
    :type image_name: str
    :param tags: List of tag attribute details
    :type tags: list[~azure.containerregistry.models.TagAttributesBase]
    """

    _attribute_map = {
        'registry': {'key': 'registry', 'type': 'str'},
        'image_name': {'key': 'imageName', 'type': 'str'},
        'tags': {'key': 'tags', 'type': '[TagAttributesBase]'},
    }

    def __init__(self, *, registry: str=None, image_name: str=None, tags=None, **kwargs) -> None:
        super(TagList, self).__init__(**kwargs)
        self.registry = registry
        self.image_name = image_name
        self.tags = tags
