# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TagAttributesBase(Model):
    """Tag attribute details.

    :param name: Tag name
    :type name: str
    :param digest: Tag digest
    :type digest: str
    :param created_time: Tag created time
    :type created_time: str
    :param last_update_time: Tag last update time
    :type last_update_time: str
    :param signed: Is signed
    :type signed: bool
    :param changeable_attributes: Changeable attributes
    :type changeable_attributes:
     ~azure.containerregistry.models.ChangeableAttributes
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'digest': {'key': 'digest', 'type': 'str'},
        'created_time': {'key': 'createdTime', 'type': 'str'},
        'last_update_time': {'key': 'lastUpdateTime', 'type': 'str'},
        'signed': {'key': 'signed', 'type': 'bool'},
        'changeable_attributes': {'key': 'changeableAttributes', 'type': 'ChangeableAttributes'},
    }

    def __init__(self, *, name: str=None, digest: str=None, created_time: str=None, last_update_time: str=None, signed: bool=None, changeable_attributes=None, **kwargs) -> None:
        super(TagAttributesBase, self).__init__(**kwargs)
        self.name = name
        self.digest = digest
        self.created_time = created_time
        self.last_update_time = last_update_time
        self.signed = signed
        self.changeable_attributes = changeable_attributes
