# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .manifest_py3 import Manifest


class V1Manifest(Manifest):
    """Returns the requested V1 manifest file.

    :param schema_version: Schema version
    :type schema_version: int
    :param architecture: CPU architecture
    :type architecture: str
    :param name: Image name
    :type name: str
    :param tag: Image tag
    :type tag: str
    :param fs_layers: List of layer information
    :type fs_layers: list[~azure.containerregistry.models.FsLayer]
    :param history: Image history
    :type history: list[~azure.containerregistry.models.History]
    :param signatures: Image signature
    :type signatures: list[~azure.containerregistry.models.ImageSignature]
    """

    _attribute_map = {
        'schema_version': {'key': 'schemaVersion', 'type': 'int'},
        'architecture': {'key': 'architecture', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'tag': {'key': 'tag', 'type': 'str'},
        'fs_layers': {'key': 'fsLayers', 'type': '[FsLayer]'},
        'history': {'key': 'history', 'type': '[History]'},
        'signatures': {'key': 'signatures', 'type': '[ImageSignature]'},
    }

    def __init__(self, *, schema_version: int=None, architecture: str=None, name: str=None, tag: str=None, fs_layers=None, history=None, signatures=None, **kwargs) -> None:
        super(V1Manifest, self).__init__(schema_version=schema_version, **kwargs)
        self.architecture = architecture
        self.name = name
        self.tag = tag
        self.fs_layers = fs_layers
        self.history = history
        self.signatures = signatures
