# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .manifest_py3 import Manifest


class V2Manifest(Manifest):
    """Returns the requested Docker V2 Manifest file.

    :param schema_version: Schema version
    :type schema_version: int
    :param media_type: Media type for this Manifest
    :type media_type: str
    :param config: V2 image config descriptor
    :type config: ~azure.containerregistry.models.Descriptor
    :param layers: List of V2 image layer information
    :type layers: list[~azure.containerregistry.models.Descriptor]
    """

    _attribute_map = {
        'schema_version': {'key': 'schemaVersion', 'type': 'int'},
        'media_type': {'key': 'mediaType', 'type': 'str'},
        'config': {'key': 'config', 'type': 'Descriptor'},
        'layers': {'key': 'layers', 'type': '[Descriptor]'},
    }

    def __init__(self, *, schema_version: int=None, media_type: str=None, config=None, layers=None, **kwargs) -> None:
        super(V2Manifest, self).__init__(schema_version=schema_version, **kwargs)
        self.media_type = media_type
        self.config = config
        self.layers = layers
